# Generated by Django 4.0.5 on 2024-02-03 14:17

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('userId', models.UUIDField(default=uuid.UUID('7fb5cf3e-e7a2-4a28-93ec-bc26673a6c06'), unique=True)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2024, 2, 3, 19, 47, 47, 638545))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2024, 2, 3, 19, 47, 47, 638545))),
            ],
        ),
    ]
